logging:
  level:
    ROOT: WARN
    tech.kitucode: DEBUG
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/recommender?useUnicode=true&characterEncoding=utf8
    username: root
    password: 'kitunda2018'
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

application:
  notify-url: http://mwandishi.co.ke:8041/api/
  notify-key: a2VrZWtyZWF0aXZlc0BnbWFpbC5jb206aWZyYmFpdXRicXdoY3Fmeg==
  config-path: /home/kitunda/Documents/Projects/recommender/config/

